services:
  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

    ports:
      - "8080:8000"

    depends_on:
      - catalogDB

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8000

      DatabaseSettings__ConnectionString: mongodb://catalogDB:27017?readPreference=primary&ssl=false
      DatabaseSettings__DatabaseName: CatalogDb
      DatabaseSettings__ProductCollection: Products
      DatabaseSettings__ProductBrandsCollection: Brands
      DatabaseSettings__ProductTypesCollection: Types

  catalogDB:
    image: mongo
    container_name: catalogDB

    ports:
      - "27017:27017"

    volumes:
      - catalogData:/data/db

  basket.api:
    image: basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile

    ports:
      - "8081:8000"

    depends_on:
      - basketDB

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8000

      CacheSettings__ConnectionString: basketDB:6379
      DiscountGrpcSettings__ServiceUrl: http://discount.grpcservice:8000

  basketDB:
    image: redis:alpine
    container_name: basketDB

    restart: always

    ports:
      - "6379:6379"
        
        
  discount.grpcservice:
    image: discount.grpcservice
    build:
      context: .
      dockerfile: Services/Discount/Discount.GrpcService/Dockerfile
    container_name: discount.service
    depends_on:
      discountDb:
        condition: service_healthy
    ports:
      - "8002:8000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8000
      NpgsqlSettings__ConnectionString: Host=discountDb;Port=5432;Database=DiscountDb;Username=admin;Password=admin@1
  
  
  discountDb:
    image: postgres:16
    container_name: discount-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin@1
      POSTGRES_DB: DiscountDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d DiscountDb" ]
      interval: 5s
      timeout: 5s
      retries: 5
      
  ordering.api:
    image: ordering.api
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

    container_name: ordering-api

    ports:
      - "8083:8000"

    depends_on:
      orderDb:
        condition: service_healthy

    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: http://+:8000

      OrderingDbSettings__ConnectionString: "Server=orderDb,1433;Database=OrderDb;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;"

  orderDb:
    image: mcr.microsoft.com/mssql/server:2022-latest

    container_name: order_sqlserver

    restart: always

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}

    ports:
      - "1433:1433"

    volumes:
      - ordering_data:/var/opt/mssql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '${MSSQL_SA_PASSWORD}' -C -Q 'SELECT 1' || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: discount-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin@1
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - discountDb
        
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9443:9443"
    volumes:
      - portainer_data:/data
    

volumes:
  catalogData:
  portainer_data:
  postgres_data:
  pgadmin_data:
  ordering_data: